alias tf='terraform'
alias tfp='tf plan'
alias tfrun='tf apply run.plan'
alias tfr='tf apply run.plan'
alias tfw='tf workspace'
alias tfws='tf workspace select'
alias tfi='tf init'
alias tfout='tf output'
