#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

# find the installers and run them iteratively
if [ "$(uname -s)" == "Darwin" ] then
  find . -name install.osx.sh | while read installer ; do sh -c "${installer}" ; done
elif [ "$(uname -s)" == "Linux" ] then
  find . -name install.linux.sh | while read installer ; do sh -c "${installer}" ; done
fi
